# Generated by Django 4.2.10 on 2024-03-21 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveSmallIntegerField(verbose_name='порядковый номер')),
                ('name_module', models.CharField(max_length=50, verbose_name='название модуля')),
                ('description', models.TextField(verbose_name='описание модуля')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/', verbose_name='картинка модуля')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='курс модуля')),
            ],
        ),
    ]
