# Generated by Django 4.2.10 on 2024-03-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения'),
        ),
    ]
