# Generated by Django 4.2.10 on 2024-03-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rubrics', models.CharField(choices=[('Введение в Git', 'Введение в Git'), ('Введение в Postgres', 'Введение в Postgres'), ('Введение в Django', 'Введение в Django')], max_length=100, verbose_name='рубрики')),
                ('theme', models.CharField(max_length=100, verbose_name='темы')),
                ('text', models.TextField(verbose_name='текст')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
