# Generated by Django 4.2.10 on 2024-04-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': 'текст', 'verbose_name_plural': 'тексты'},
        ),
    ]
