# Generated by Django 4.2.10 on 2024-04-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(max_length=50, verbose_name='название курса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='картинка курса')),
                ('description', models.CharField(max_length=500, verbose_name='описание курса')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='цена курса')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lesson', models.CharField(max_length=50, verbose_name='название урока')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/', verbose_name='картинка урока')),
                ('description', models.TextField(verbose_name='описание урока')),
                ('content', models.TextField(verbose_name='содержание урока')),
                ('link', models.CharField(max_length=200, verbose_name='ссылка на видео')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveSmallIntegerField(verbose_name='порядковый номер')),
                ('name_module', models.CharField(max_length=50, verbose_name='название модуля')),
                ('description', models.TextField(verbose_name='описание модуля')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/', verbose_name='картинка модуля')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
            ],
        ),
    ]
