# Generated by Django 4.2.10 on 2024-04-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_materials', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'модуль', 'verbose_name_plural': 'модули'},
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ссылка на картинку'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ссылка на картинку'),
        ),
        migrations.AlterField(
            model_name='module',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ссылка на картинку'),
        ),
    ]
